Repository ossamamehmood/Hacktoberfest, pull requests merged in 2022-09, with the labels that each got.

#26 Add Ebenezer Akhonya as a contributer
  content/participant/ebenezerAkhonya.md
  static/images/Ebenezer.png
Labels: hacktoberfest-accepted

#27 Added my details(Harish2930) to the repo
  content/participant/Harish2930.md
  static/images/Harish2930.png
Labels: hacktoberfest-accepted

#28 Hussain_14 branch
  content/participant/Hussain_14.md
  readme.md
  static/images/Hussain Lohawala.jpg
Labels: enhancement, hacktoberfest-accepted

#29 add mariorodrigues10/mariorodrigues
  content/participant/Mariorodrigues10.md
  static/images/MárioRodrigues.jpg
Labels: hacktoberfest-accepted

#47 Added my credentials for Hacktoberfest 2022
  content/participant/shivam-jha2712.md
  static/images/shivam-jha2712.jpg
Labels: hacktoberfest-accepted, hacktoberfest

#45 Create thepratikgyawali.md
  thepratikgyawali.md
Labels: hacktoberfest-accepted, hacktoberfest

#43 added myself
  content/participant/Shruti.md
  static/images/shruti.jpg
Labels: hacktoberfest-accepted, hacktoberfest

#30 added myself
  content/participant/matildeopbravo.md
  static/images/matildeopbravo.jpg
Labels: hacktoberfest-accepted, hacktoberfest

#31 added myself
  content/participant/AnshTandon0.md
  content/participant/AroobaFatimah.md
  static/images/AnshTandon0.jpeg
Labels: hacktoberfest-accepted, hacktoberfest

#42 Added Myself
  content/participant/devnarayanp02
  static/images/devnarayanp02.jpg
Labels: hacktoberfest-accepted, hacktoberfest

#41 added thititongumpun
  content/participant/thititongumpun.md
  static/images/Thititongumpun.png
Labels: hacktoberfest-accepted, hacktoberfest

#32 added myself
  content/participant/Tarun-108.md
  static/images/Tarun-108.jpg
Labels: hacktoberfest-accepted, hacktoberfest

#33 added myself
  content/participant/sudhatanay.md
  static/images/picture.jpeg
Labels: hacktoberfest-accepted, hacktoberfest

#34 Hii Accept my PR
  content/participant/Sergi0456. md
  static/images/sergi0456.jpg
Labels: hacktoberfest-accepted, hacktoberfest

#36 Pull request_01
  content/participant/rhilican.md
  static/images/rhilican.jpg
Labels: hacktoberfest-accepted, hacktoberfest

#37 added myself
  content/participant/samuuuh.md
  static/samuuuh.png
Labels: hacktoberfest-accepted, hacktoberfest

#39 Added myself
  content/participant/nitin-pandita.md
  static/images/nitin-pandita.png
Labels: hacktoberfest-accepted, hacktoberfest

#48 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted, hacktoberfest

#52 Update
  content/participant/Shruti.md
  static/images/shruti.jpg
Labels: hacktoberfest-accepted, hacktoberfest

#74 Added Myself
  content/participant/nitin-pandita.md
  static/images/nitin pandita.png
Labels: hacktoberfest-accepted, hacktoberfest
